### ISSUE TITLE
Click/Type, Screenshot at predetermined times

### ISSUE THREAD

**Issue by subwaymatch** [subwaymatch/trackbrowser-client#11]
Hobson, Jessen L
4:33 AM (2 hours ago)

to me 
One problem I have is that if someone is searching in google, I cannot see what they are searching unless they navigate away from the page or scroll. Only scroll and navigation events trigger screen shots, right? How hard would it be to record a screen shot and event on (1) a click and (2) typing?

Also, how hard would it be and how much space would it take up to take screen shots at predetermined times? For example, what if a screen shots were taken on the following intervals until a new event is recorded: 1 minute since last event, then 2 minutes later, then 3 minutes later, then 5 minutes later, then 8 minutes later, then 13 minutes later, then 21, 34, 55, 89, etc. following the Fibonacci sequence?

These can obviously be new features for a later version. I would still like to roll out a mostly complete mac and PC version this weekend, or at least by Monday.

Jessen

**Comment by subwaymatch** [comment]
1) What happens when a user clicks on a blank area of the webpage? Do you still want the event/screenshot to be recorded? 

2) We can record what the user has typed into a text box - working progress. 

3) Screenshots with intervals of Fibonacci sequence will be added - working progress. 

Currently, the disk space in trackbrowser server is 26% full (7.3GB out of 21GB).

**Comment by subwaymatch** [comment]
Click event recording added via 85f96dbe89328417e268a20f2c39c411701fd11e

**Comment by subwaymatch** [comment]
Fibonacci sequence screenshot added via 7064a23e9de75374bb72053d268a2a4ef125774f, dcb69bb93a3cd9f534ea3e1f83e184eef70279a5

The fibonacci timer is paused when the application is inactive. This is a default behavior of Chromium.

**Comment by Jessen7** [comment]
What does "inactive" mean specifically? How does the browser know it is inactive? If it means that a different window is actively being used, than that is fine, we can pause screen shots. If it means that no action has happened in the browser for some time but the browser is still being used (e.g., the user is reading or viewing a video), then let's try to keep taking Fibonacci-times screen shots.

Regarding your list above:
1) No
3) Thank you. Please update me when it gets 1/2 full.

Thanks Park!

**Comment by subwaymatch** [comment]
I'm not home over this weekend. I will send an updated version next week.

**Comment by subwaymatch** [comment]
Currently working on in-page find functionality (Chrome-like behavior)
685008534381edc636cc178277e4e6cfc8d3a34e
c8e44e6573d234d9df857a6a5f92b138eb9ec2c6
0b6eaf9929fdeb25a33ea510fc1bc83f710143be

**Comment by subwaymatch** [comment]
Fibonacci screenshot test
![image](https://cloud.githubusercontent.com/assets/1064036/13689126/f4f20d28-e769-11e5-8690-d74f534f3429.png)

**Comment by subwaymatch** [comment]
"Find in page" functionality update 
f3f42a1da0bb9dc0d5f0fbcd6f005e8c67eecf21

**Comment by subwaymatch** [comment]
Instead of recording every typing event to the server, the text value of the input elements will be recorded once the user has done typing. Also, "Find" feature has been updated again. 

cb3ed9acc6b93c5759add8a629d2c53508bbb609

**Comment by subwaymatch** [comment]
Typing event export test
![image](https://cloud.githubusercontent.com/assets/1064036/13730350/f24b3a4a-e98f-11e5-87a0-412cb786658e.png)

![image](https://cloud.githubusercontent.com/assets/1064036/13730356/1440066c-e990-11e5-81a8-4628194883fd.png)

**Comment by subwaymatch** [comment]
Capturing screenshots with very short intervals cause some screenshots to be skipped. 

![image](https://cloud.githubusercontent.com/assets/1064036/13730376/8f9a1c1c-e990-11e5-9cb5-9e90d2398696.png)

**Comment by subwaymatch** [comment]
Local updates pushed to Github for packaging v7-alpha

14b5b0a5089dae434baade16d4ff1ae6596d3ee1 - Record input data to server
b1d4a5354aa7f33cb7ba1d0687fcaef41c2ffd16 - Limit the number of screenshots when multiple events are fired within very short period of time

**Comment by subwaymatch** [comment]
Closing issue along with the release of v7
https://github.com/subwaymatch/trackbrowser-client/releases/tag/v7
