### ISSUE TITLE
No events recorded when moving from tab to tab

### ISSUE THREAD

**Issue by Jessen7** [subwaymatch/trackbrowser-client#12]
...on this website: https://github.com/subwaymatch/trackbrowser-client

E.g., no event recorded when move from https://github.com/subwaymatch/trackbrowser-client to
here https://github.com/subwaymatch/trackbrowser-client/issues to
here https://github.com/subwaymatch/trackbrowser-client/pulls, etc.

**Comment by subwaymatch** [comment]
Chromium doesn't fire regular navigation events for in-page navigation. I will add a workaround in v7.

**Comment by subwaymatch** [comment]
Feature added via 2d078a1d356da49dd747ade517f53f49ba71b1d9. In-page navigation events are now recorded. 

Taking screenshots for in-page navigation has been turned off as there is no way to find out when the in-page navigation has been fully rendered. For example, when clicking on "pulls" tab in "issues" tab in Github, Chromium does not fire any event for "load complete".
