### ISSUE TITLE
require input for Research Topic entry

### ISSUE THREAD

**Issue by Jessen7** [subwaymatch/trackbrowser-client#13]
This is not critical now, but it would be nice to _not_ have a default for the entry for Research Topic. right now, if they user does nothing, "buy a new company" is automatically selected. It would be nice if nothing was selected by default so the user has to select something each time.

**Comment by subwaymatch** [comment]
Default selection has been removed via 1ce31c58f25ee983f899049bf468fc1a7e9bf9c4
