### ISSUE TITLE
Mac version not working with newest OS

### ISSUE THREAD

**Issue by Jessen7** [subwaymatch/trackbrowser-client#16]
[Mac Browser Issues.pdf](https://github.com/subwaymatch/trackbrowser-client/files/730391/Mac.Browser.Issues.pdf)
![screen shot 2017-01-21 at 13 04 40](https://cloud.githubusercontent.com/assets/6330785/22300676/d4551dd2-e2ed-11e6-8788-0945481e3508.png)
[Mac Browser Issues2.pdf](https://github.com/subwaymatch/trackbrowser-client/files/730411/Mac.Browser.Issues2.pdf)

**Comment by subwaymatch** [comment]
Seems to be an issue with newer versions of MacOS... will get it fixed ASAP

**Comment by subwaymatch** [comment]
Need to bump TrackBrowser's components with newest versions.

**Comment by subwaymatch** [comment]
Commited b86873eea9953903e4936cb496975fd9f53102a9 to repackage TrackBrowser with updated component versions

**Comment by subwaymatch** [comment]
<img width="893" alt="screen shot 2017-01-30 at 7 11 08 am" src="https://cloud.githubusercontent.com/assets/1064036/22433135/6c4c7b14-e6bb-11e6-9805-79ac3191b1ad.png">

**Comment by subwaymatch** [comment]
Uploaded a fixed version to [tb-app9.1-mac.zip](https://github.com/subwaymatch/trackbrowser-client/releases/download/v9/tb-app9.1-mac.zip), closing issue
