### ISSUE TITLE
Cannot watch video

### ISSUE THREAD

**Issue by subwaymatch** [subwaymatch/trackbrowser-client#4]
Hobson, Jessen L
12:55 AM (0 minutes ago)

to me 
Using the version 3, I cannot watch the video here: A screenshot was uploaded for page http://finance.yahoo.com/news/the-markets-expects-more-volatility-for-some-time-to-come-201946848.html.

**Comment by subwaymatch** [comment]
Need to check whether the video plays normally in other browsers.

**Comment by subwaymatch** [comment]
Hobson, Jessen L
1:06 AM (9 minutes ago)

to me 
I could watch it in chrome although it was black in chrome at the beginning. But if I clicked on it it worked.

**Comment by subwaymatch** [comment]
~~I will need to find a different PC to work on this issue as I can't get the video player to work in Chrome.~~
The flash content loads after a very long wait. 

![2016-02-03 01_17_40-the market expects more volatility for some time to come - yahoo finance](https://cloud.githubusercontent.com/assets/1064036/12755775/3186378c-ca14-11e5-8100-3156a1201334.png)

![2016-02-03 01_18_32-the market expects more volatility for some time to come - yahoo finance](https://cloud.githubusercontent.com/assets/1064036/12755776/3188f58a-ca14-11e5-85e6-f436f698a033.png)

**Comment by subwaymatch** [comment]
As it turns out, Adobe Flash player is not supported TrackBrowser application's underlying browser engine (Chromium). 

> Chromium is the open-source web browser project from which Google Chrome draws its source code. The browsers share the majority of code and features, though there are some minor differences in features and they have different licensing.
> (Wikipedia)

One of the differences in features between Chromium and Chrome is that Chrome has a built-in Flash Player (similar to how Chrome has a built-in PDF viewer). Chrome has deprecated old APIs required to play Flash contents through Adobe's traditional Flash Player (known as NPAPI). 

> In the short term, end users and enterprise administrators will be able to whitelist specific plug-ins. Eventually, however, NPAPI support will be completely removed from Chrome. We expect this to happen before the end of 2014, but the exact timing will depend on usage and user feedback. Note that the built-in Flash plug-in and PDF viewer will be unaffected because they don’t use NPAPI.
> http://blog.chromium.org/2013/09/saying-goodbye-to-our-old-friend-npapi.html

Since TrackBrowser uses Chromium, Adobe Flash isn't loading. **Window users may have to install an external .exe file to get the Flash Player to work in TrackBrowser. For Mac, I can't tell if this workaround would work.**

# 

A very similar issue can be found at:
https://github.com/atom/electron/issues/2597

**Comment by Jessen7** [comment]
So. How long would it take to put that together? Could it be a part of the download or does it have to be separately run?

**Comment by subwaymatch** [comment]
It has to be a separate install. Addition for Windows can be done in two days. For Mac, I'm guessing another day.

**Comment by subwaymatch** [comment]
Flash version check page: 
http://www.adobe.com/software/flash/about/

**Comment by subwaymatch** [comment]
Flash player isn't working even with external install - I am going to leave this out from v6

**Comment by subwaymatch** [comment]
Flash player will be supported in the next release (28de90c501fed2e8c8ed1055c0b2d5ecf2746bdf)

![image](https://cloud.githubusercontent.com/assets/1064036/13386735/f7935408-def2-11e5-82f4-98c805684793.png)
