### ISSUE TITLE
Issues from Joseph Burke

### ISSUE THREAD

**Issue by subwaymatch** [subwaymatch/trackbrowser-client#6]
Burke, Joseph William jwburke2@illinois.edu
1:37 AM (32 minutes ago)

to me 
Overall, browser was easy to use and functioned as quickly and efficiently as my other browsers.  See noted issues below:

1)      When using the browser, there is no search function (and ctrl+f does not work).  This is pretty important for me – especially when reviewing longer documents online (quick find).

2)      When you right click on a link you have two options – open link in new “tab” and open link in new “window”.  Both options simply open the link in a new tab.  This is another function I use – I often open links in new “windows” so I can alt+tab through them to compare information.

3)      The three line button on the far right of the URL input area (general indicating a drop down “options” type menu), does not do anything.  Only reporting this because I’m not sure if it is supposed to lead to additional features.

4)      A few times I was interested in viewing video clips (presentations or news clips about a company), however I couldn’t access the video as it stated Adobe version xxx was needed.  I was able to open the same video when in my other browsers.  Here is an examples:  http://abcnews.go.com/Technology/video/googles-parent-company-passes-apple-valuable-36662698

5)      The website seekingalpha.com was very slow to load compared to my other browsers.  Not sure why – but I hypothesize it has something to do with the number of ads on the sides of the website.  Was still very usable – just noticeably slower.

**Comment by subwaymatch** [comment]
1) In-page search functionality will take at least (probably longer) a week to implement. I will need to check with Dr. Hobson to see if he would like the feature in the browser. 

2) Opening in new window is currently unsupported due to tracking feature. I will remove the "Open in new tab" from the right-click menu. 

3) The "options" menu button was placed in case additional menu items were to be added, but haven't been used. I will remove the button since it isn't doing anything as you've mentioned. 

4) Adobe Flash contents are not supported. 

This browser application uses Chrome's internal engine (Chromium) to emulate a browser, but Adobe Flash has been deprecated in latest versions of Chromium. *_I will look for workarounds regarding this issue. *_

5) It's probably due to screenshots being taken when scrolling from the application.

**Comment by subwaymatch** [comment]
2), 3) has been resolved through f2b6fc757b986e608738a7e690d6d9ce73fcfaf2

**Comment by Jessen7** [comment]
> Park - no need to respond to Joe--just respond to me. 
> 1) In-page search functionality will take at least (probably longer) a week to implement. I will need to check with Dr. Hobson to see if he would like the feature in the browser.
> don't do this. It will take too long and is not worth the effort.

2) Opening in new window is currently unsupported due to tracking feature. I will remove the "Open in new tab" from the right-click menu.

> This is done, then.

3) The "options" menu button was placed in case additional menu items were to be added, but haven't been used. I will remove the button since it isn't doing anything as you've mentioned.

> Great

4) Adobe Flash contents are not supported.

> I wish this worked. Please continue to work on this to see how long it would take to fix (with the separate download or something that is easier).

This browser application uses Chrome's internal engine (Chromium) to emulate a browser, but Adobe Flash has been deprecated in latest versions of Chromium. *I will look for workarounds regarding this issue. *

5) It's probably due to screenshots being taken when scrolling from the application.

> OK

**Comment by subwaymatch** [comment]
Flash player support issue is open at #4 - will close this one.
